### ISSUE TITLE
Defining table by resource name

### ISSUE THREAD

**Issue by martinglover** [medikoo/serverless-plugin-dynamodb-autoscaling#4]
I've the situation where my table name is defined based on the environment I'm deploying to. 

However as you are unable to define a variable as the key, it would be very useful to be able to define the Resource name in the table config as the table key, rather than the table name.

ie
Table name
custom:
  dynamodbAutoscaling:
    tablesConfig:
      dynamodb_table_name:
        minCapacity: 10

Resource name
custom:
  dynamodbAutoscaling:
    tablesConfig:
      ResourceTableName:
        minCapacity: 10

**Comment by medikoo** [comment]
@martinglover it's not well documented but you can use glob patterns (they're resolved by [minimatch](https://www.npmjs.com/package/minimatch)), so technically you can use `*SomePostfix` in place of table names.

Would that solve this issue for you?

I've also added hint to documentation stating that's possible.

**Comment by martinglover** [comment]
@medikoo Thanks you very much that worked perfectly
